### ISSUE TITLE
helm-flx breaks TRAMP

### ISSUE THREAD

**Issue by syl20bnr** [PythonNut/helm-flx#10]
When initiating an ssh connection through `helm-find-files` I get the error:

```
Error running timer: (wrong-type-argument listp "/ssh:sbenner@10.140.33.8:/home/sbenner/.")
```

I can still manage to open a remote buffer but I have not real-time candidates provided by Helm. Once I'm in a remote buffer whenever I invoke `helm-find-files` I get this error:

```
mapcar: Wrong type argument: listp, "/ssh:sbenner@10.140.33.8:/home/sbenner/."
```

Desinstalling `helm-flx`fixes the issues.

**Comment by PythonNut** [comment]
Hm... That's unfortunate, as the helm timer is notoriously hard to debug. I'll take a look tonight and report back.
