### ISSUE TITLE
Arbitrary word order highlighting

### ISSUE THREAD

**Issue by Pitometsu** [PythonNut/helm-flx#12]
`M-x file find`
with plain [helm](https://github.com/emacs-helm/helm/issues/1251#issuecomment-152449877) highlight both matches.
with `helm-flx` -- the `file` only.

**Comment by PythonNut** [comment]
Hm... This used to work, by some of my old compatibility code is now out-of-sync. 

I going to do the right thing this time and forward it to the default function, so I won't run into these issues again.

**Comment by Pitometsu** [comment]
Thank you, it work now.
