### ISSUE TITLE
Does not work anymore since recent helm commit (find-files / M-x)

### ISSUE THREAD

**Issue by pbmtp** [PythonNut/helm-flx#14]
Hi,

I am a happy user of helm-flx and helm-fuzzier. Since this commit helm-flx does not seem to work like before for find-file and M-x

https://github.com/emacs-helm/helm/commit/1de1701c73b15a86e99ab1c5c53bd0e8659d8ede

I tried setting back helm-completing-read-handlers-alist to previous version but it does not seem to work like before so maybe some more commits are responsible for the change of way of working.

Could you take a look and comment on this issue ?

Thanks in advance
Damien

**Comment by PythonNut** [comment]
Thanks for the report. I'll look into it.

**Comment by pbmtp** [comment]
Hi,

thanks

here is the code i used to "revert" the modification but find-files seem not be back to flx state (no  coloring for example).

```
    (delete '(find-file . nil) helm-completing-read-handlers-alist)
    (delete '(execute-extended-command . nil) helm-completing-read-handlers-alist)
```

If you need me to do some test do not hesitate
Damien

**Comment by PythonNut** [comment]
Our of curiosity, do `helm-find-files` and `helm-M-x` still work? 

After you execute that code, does toggling `helm-mode` fix it?

Sorry I can't do much more. My schoolwork is pretty crazy right now. The weekend approacheth, however.

**Comment by pbmtp** [comment]
Hi,

it does not seem to change anything. I cant remember if coloring worked in find-files earlier. Spaces are allowed and do partial match so i assume it is helm fuzzy matching that is used.
If you need i can do more tests.

No stress, take your time for your schoolwork.
Damien

**Comment by PythonNut** [comment]
@pbmtp 

As far as I can tell, `execute-extended-command` and `helm-M-x` seem to be working fine. 

`helm-find-files` also has correct sorting, but no highlighting. As far as I know, this was always the case, although I could be wrong.

**Comment by pbmtp** [comment]
Hi,

thanks for test and report, indeed sorting work in find-files but no highlight

Damien

**Comment by PythonNut** [comment]
In that case, I don't think anything has changed. I'll close this issue, and, if you want, you can open a new one regarding the missing highlighting in `find-files`.

**Comment by pbmtp** [comment]
Sure go for it thanks for this great project

**Comment by pbmtp** [comment]
Saw you added highlight in find-file thanks a lot ;)

**Comment by PythonNut** [comment]
@pbmtp yup. It's a huge hack, but it works, and I'm happy. Do tell if there's anything wrong, though.
