### ISSUE TITLE
helm-candidate-number-limit

### ISSUE THREAD

**Issue by StreakyCobra** [PythonNut/helm-flx#16]
When I set `helm-candidate-number-limit` to `nil`, I get an error from `helm-flx`:

```
Error running timer: (wrong-type-argument number-or-marker-p nil)
```

I haven't manage to get the content of the backtrace, so here is a screenshot :pensive: 

![backtrace](https://i.imgur.com/XDb9dJI.png)

I'm using Spacemacs if relevant. Let me know if I can give more information in any way. If it's not a bug on your side, then feel free to close this issue :-)

**Comment by PythonNut** [comment]
Thanks. I'm pretty sure it's an issue on my side. I've never seen `helm-candidate-number-limit` set to `nil`,  because of potential performance problems, but I should be able to handle that case without much trouble.

**Comment by PythonNut** [comment]
Alright, should be fixed.

**Comment by StreakyCobra** [comment]
Thanks for the fast answer and fix, amazing :+1: I'll test it once updated on MELPA :-)

**Comment by StreakyCobra** [comment]
It's working now, thansk a lot!
