### ISSUE TITLE
Support helm-locate

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/helm-flx#17]
I don't personally have `(setq helm-locate-fuzzy-match t)` enabled, so this isn't an issue for me.

**Comment by PythonNut** [comment]
This is quite tricky since `helm-source-locate` seems to append the candidates incrementally in batches. However, `:filtered-candidate-transformer` seems to be only called on the new candidates, not the entire set of candidates, so it's not possible to move a high-scoring candidate above the top of the group it was added in, which means that the best I can currently do is sort into "clumps" as the data arrives, but not globally.

@thierryvolpiatto is there any easy way to work around this?

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> This is quite tricky since helm-source-locate seems to append the candidates incrementally in batches. However, :filtered-candidate-transformer seems to be only
> called on the new candidates, not the entire set of candidates, so it's not possible to move a high-scoring candidate above the top of the group it was added in,
> which means that the best I can currently do is sort into "clumps" as the data arrives, but not globally.
>
> @thierryvolpiatto is there any easy way to work around this?

Try to use candidate-transformer instead of
filtered-candidate-transformer.

-- 
Thierry

**Comment by PythonNut** [comment]
@thierryvolpiatto the results look about the same. Here is the code I'm using:

```emacs
;; -*- lexical-binding: t -*-
(setq helm-locate-fuzzy-match t)

(setq helm-source-locate
      (helm-make-source "Locate" 'helm-locate-source
        :pattern-transformer 'helm-locate-pattern-transformer
        :candidate-transformer #'helm-flx-helm-locate-sort-candidates))

;; this just does the sorting
(defun helm-flx-helm-locate-sort-candidates (candidates)
  (require 'flx)
  (helm-flx-sort candidates helm-input
                 #'cdr
                 (lambda (pattern display-string-fn)
                   (lambda (cand)
                     (cons (cons (format "%d %s"
                                         (or (car (flx-score
                                                   (file-name-nondirectory (cdr cand))
                                                   pattern
                                                   helm-flx-cache))
                                             most-negative-fixnum)
                                         (car cand))
                                 (cdr cand))
                           (or (car (flx-score
                                     (file-name-nondirectory (cdr cand))
                                     pattern
                                     helm-flx-cache))
                               most-negative-fixnum))))))

(setf (alist-get 'candidate-transformer helm-source-locate)
      (append (alist-get 'candidate-transformer helm-source-locate)
              (list #'helm-flx-helm-locate-sort-candidates)))
```

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto the results look about the same.

Hmm, yes indeed, sorting with async is actually not possible on the
whole list of candidates which would have to be redisplayed from
sentinel once process finished, which is not implemented yet.

--
Thierry
