### ISSUE TITLE
Please release helm-flx on MELPA Stable

### ISSUE THREAD

**Issue by ghost** [PythonNut/helm-flx#18]
helm-flx hasn't been released on [MELPA stable](https://stable.melpa.org) yet. Please consider releasing it on [MELPA stable](https://stable.melpa.org).

**Comment by nickserv** [comment]
You can work around this by adding both MELPA and MELPA stable to your package archives.

If the package author would like to support stable versioning, they can do this through git tags, assuming master is stable and versioning starts at 1.0.0:

```sh
$ git tag v1.0.0
$ git push origin v1.0.0
```

**Comment by PythonNut** [comment]
My hesitation to tag a release essentially stems from the fact that this is actually a horrifying hack. I don't feel comfortable asserting that this package is "stable" and won't break things.

**Comment by ghost** [comment]
@PythonNut I guess that that makes sense. I've also found that I can use packages from both MELPA and MELPA Stable at the same time and I've been using that to use this package from MELPA while using what I can from MELPA Stable.
