### ISSUE TITLE
Please make available for Emacs 25.1

### ISSUE THREAD

**Issue by rrthomas** [PythonNut/helm-flx#19]
This package requires Emacs 24.4. I presume that's why it doesn't show up for me on Emacs 25.1 on MELPA?

**Comment by nickserv** [comment]
I'm using Emacs 25.1 and I see it on MELPA. Is your issue fixed, or are you perhaps missing it from MELPA stable?

**Comment by rrthomas** [comment]
You've got it, I meant MELPA stable.

**Comment by nickserv** [comment]
Ah okay, this seems like a duplicate of #18 then. You might be able to get around this by adding both normal and stable MELPA to your package archive list, giving a higher priority to stable for other packages.

**Comment by rrthomas** [comment]
Yes, it is (I didn't realise at first, I thought it might be a version-compatibility thing). I have used the fix you suggested, and it's working; thanks.

**Comment by PythonNut** [comment]
See the resolution to #18.
