### ISSUE TITLE
Experiencing limited flx completion in helm-M-x

### ISSUE THREAD

**Issue by nickserv** [PythonNut/helm-flx#20]
First off, I'm a relatively new emacs user so I apologize if I'm missing something or leaving a misleading issue.

After installing helm-flx and enabling it through customize, I notice that I can type acronyms to complete most entries in most of my usages of helm (for example, `M-x customize-variable RET hfm` completes to `helm-flx-mode`). However, this completion doesn't seem to work with my `helm-M-x` setup (which I have bound to `M-x` by default). Since `M-x` is so common I assumed that I missed something when setting up this package and/or helm. Is this supposed to work with `helm-M-x` or is it a limitation with that source?

**Comment by PythonNut** [comment]
That's unusual, `helm-M-x` seems to work in `emacs -Q` with `helm-flx-mode` enabled.

I'm sorry I don't have more time to look into it. Finals are in a few days.

**Comment by nickserv** [comment]
No rush, I feel your pain. It's probably just an issue with my config anyway, I will let you know if I figure out how to reproduce it (or you can view [my `.emacs.d`](https://github.com/nickmccurdy/dotfiles/tree/master/home/.emacs.d)).

**Comment by PythonNut** [comment]
I haven't heard anything about this, so I'm closing this for now.
