### ISSUE TITLE
Explain Caveats

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/helm-flx#3]
- Doesn't work in sources that don't support fuzzy matching to begin with
- ~~Doesn't work in `helm-find-files`~~

**Comment by andresilva** [comment]
Hey,
Do you think making it work in `helm-find-files` is something that is feasible in the long run? (I have no knowledge about Helm's API, my only experience is as a user ;-)).

**Comment by PythonNut** [comment]
It's possible, but honestly I don't know. That part of the API wasn't designed to be extended.  

Anything can be done, it's just a matter of how much work, and how much hackiness you're willing to tolerate. 

Work will come with time. Cleanliness is an open question.

**Comment by PythonNut** [comment]
@andrebeat support for `helm-find-files` has been added. :)

**Comment by andresilva** [comment]
Wow, I didn't even have time to reply in support! Thanks for the effort.
