### ISSUE TITLE
Does helm-flx work alongside helm-adaptive?

### ISSUE THREAD

**Issue by ghost** [PythonNut/helm-flx#4]
Although flx/helm-flx fuzzy matching works very well, one remaining issue which bothers people
is that flx doesn't take into account recency and doesn't learn when you consistently
use a particular sequence to bring up a particular item even though some other items
may score higher. The `helm-adaptive` package bundled with helm should provide
this but it looks like helm-flx may be overriding it when it hijacks the sorting function,
though I'm not sure.

@PythonNut, any suggestions on how to get even better matching results with both?

**Comment by ghost** [comment]
Helm maintainer says helm-adaptive is semi-broken and fixing it isn't a priority, see issue there 
for a workaround snippet. It's working now for me.

**Comment by PythonNut** [comment]
@AlKapote Yes, I do remember `helm-adaptive-mode` being broken last I checked. 

Would you mind posting your workaround here for future wanderers?
