### ISSUE TITLE
Helm-flx breaks helm-find-files on long paths

### ISSUE THREAD

**Issue by TheBB** [PythonNut/helm-flx#9]
See https://github.com/syl20bnr/spacemacs/issues/3327#issuecomment-150109947 and the discussion that follows.

Is there a way to work around this?

**Comment by PythonNut** [comment]
Implementing DP in `flx` should fix this.

Understandably, you may want something like `helm-flx-for-helm-find-files` as (boolean) customizable variable. However, I'm hoping we can just get to the root of the issue and make everyone happy.

**Comment by PythonNut** [comment]
See https://github.com/lewang/flx/pull/75.

**Comment by PythonNut** [comment]
See also https://github.com/lewang/flx/pull/76.

**Comment by joehillen** [comment]
Does flx need to be forked? It hasn't been updated in a year.

**Comment by PythonNut** [comment]
@joehillen no indeed. I now have push access to the `flx` repo. 

If there's one thing though, I'm trying to move carefully, so I don't break things.

**Comment by EphramPerdition** [comment]
@PythonNut , the workaround in 37d8de8e9b0f7fb7a30007f31a6354e167383f2f still leaves some things broken for me.

Even with `(setq helm-flx-for-helm-find-files nil)`, when I open a file in some deep path and then hit `C-x C-f` to open another from the same directory there's a very long pause before helm appears.
Not activating `helm-flx` in the first place makes it go away.

Curiously, if I disable the `helm-flx` minor mode once it's been activated the problem persists.
It could be particular to my setup, but If it is I can't find it.

**Comment by PythonNut** [comment]
@EphramPerdition I honestly have no idea what it could be. Would you be so kind as to try profiling the event, and see what's eating up time and with what backtrace?

**Comment by EphramPerdition** [comment]
@PythonNut, It's not a deep path that triggers it, but a specific form of a directory name. The kind you find in `.emacs.d/elpa`. I think you can repro by creating a directory called `a-12345678.1234` and touching a few files within it, then find-file there. You should notice a long pause with emacs pegged at 100% cpu. The delay is proportional to the number of files in he directory, and the `.foo` suffix is necessary.

IIRC `flx` has some special case for treating file extensions of that form. Maybe something goes terribly wrong when the "file extension" is actually in the middle of a path? just a guess.

**Comment by PythonNut** [comment]
Strange, I'll look into it tomorrow.

**Comment by PythonNut** [comment]
@EphramPerdition I can see the slow behavior, but I can't seem to reproduce it with `(setq helm-flx-for-helm-find-files nil)`. Do note that you need to set the variable _before_ you activate the mode.

I'm happy to say that the new version of flx doesn't have a slowdown in the first place. :)

**Comment by PythonNut** [comment]
As of https://github.com/lewang/flx/pull/78, this should be fixed.
